from unittest import TestCase
from Node import Node
from Tree import Tree


class TestTree(TestCase):
    def test_tree_initialization(self):
        tree = Tree()
        self.assertIsNotNone(tree.root_node)
        self.assertIsNone(tree.root_node.value)
        self.assertIsNone(tree.root_node.left.value)
        self.assertIsNone(tree.root_node.right.value)

    def test_tree_insertion_root_node(self):
        tree = Tree()
        self.assertIsNotNone(tree.root_node)
        self.assertIsNone(tree.root_node.value)
        self.assertIsNone(tree.root_node.left.value)
        self.assertIsNone(tree.root_node.right.value)
        tree.insert(Node.factory(12))
        self.assertIsNotNone(tree.root_node)
        self.assertIsNotNone(tree.root_node.value)
        self.assertEqual(12, tree.root_node.value)
        self.assertIsNone(tree.root_node.left.value)
        self.assertIsNone(tree.root_node.right.value)

    def test_tree_insertion_right_node(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(15))
        self.assertIsNotNone(tree.root_node)
        self.assertIsNotNone(tree.root_node.value)
        self.assertEqual(12, tree.root_node.value)
        self.assertIsNone(tree.root_node.left.value)
        self.assertIsNotNone(tree.root_node.right.value)
        self.assertEqual(15, tree.root_node.right.value)

    def test_tree_insertion_left_node(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        self.assertIsNotNone(tree.root_node)
        self.assertIsNotNone(tree.root_node.value)
        self.assertEqual(12, tree.root_node.value)
        self.assertIsNotNone(tree.root_node.left.value)
        self.assertIsNone(tree.root_node.right.value)
        self.assertEqual(10, tree.root_node.left.value)

    def test_tree_insertion_equal_node(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(12))
        self.assertIsNotNone(tree.root_node)
        self.assertIsNotNone(tree.root_node.value)
        self.assertEqual(12, tree.root_node.value)
        self.assertIsNone(tree.root_node.left.value)
        self.assertIsNotNone(tree.root_node.right.value)
        self.assertEqual(12, tree.root_node.right.value)

    def test_tree_multi_level_insertion(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        self.assertEqual(12, tree.root_node.value)
        self.assertEqual(12, tree.root_node.right.value)
        self.assertEqual(100, tree.root_node.right.right.value)
        self.assertEqual(10, tree.root_node.left.value)
        self.assertEqual(11, tree.root_node.left.right.value)
        self.assertEqual(1, tree.root_node.left.left.value)

    def test_tree_search(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        self.assertTrue(tree.search(Node.factory(12)))
        self.assertTrue(tree.search(Node.factory(10)))
        self.assertTrue(tree.search(Node.factory(11)))
        self.assertTrue(tree.search(Node.factory(1)))
        self.assertTrue(tree.search(Node.factory(100)))
        self.assertFalse(tree.search(Node.factory(None)))
        self.assertFalse(tree.search(Node.factory(123)))
        self.assertFalse(tree.search(Node.factory(0)))
        self.assertFalse(tree.search(Node.factory(-01)))
        self.assertFalse(tree.search(Node.factory(1001)))

    def test_deletion_leaf_node(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        tree.delete(Node.factory(1))
        self.assertTrue(tree.search(Node.factory(12)))
        self.assertTrue(tree.search(Node.factory(10)))
        self.assertTrue(tree.search(Node.factory(11)))
        self.assertFalse(tree.search(Node.factory(1)))
        self.assertTrue(tree.search(Node.factory(100)))
        self.assertEqual(12, tree.root_node.value)
        self.assertEqual(12, tree.root_node.right.value)
        self.assertEqual(100, tree.root_node.right.right.value)
        self.assertEqual(10, tree.root_node.left.value)
        self.assertEqual(11, tree.root_node.left.right.value)
        self.assertEqual(None, tree.root_node.left.left.value)
        self.assertFalse(tree.root_node.left.left.value == 1)

    def test_deletion_node_with_one_child(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        tree.insert(Node.factory(99))
        tree.delete(Node.factory(100))
        self.assertTrue(tree.search(Node.factory(12)))
        self.assertTrue(tree.search(Node.factory(10)))
        self.assertTrue(tree.search(Node.factory(11)))
        self.assertTrue(tree.search(Node.factory(1)))
        self.assertFalse(tree.search(Node.factory(100)))
        self.assertTrue(tree.search(Node.factory(99)))
        self.assertEqual(99, tree.root_node.right.value)

    def test_deletion_node_with_two_children(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        tree.insert(Node.factory(99))
        tree.delete(Node.factory(10))
        self.assertTrue(tree.search(Node.factory(12)))
        self.assertFalse(tree.search(Node.factory(10)))
        self.assertTrue(tree.search(Node.factory(11)))
        self.assertTrue(tree.search(Node.factory(1)))
        self.assertTrue(tree.search(Node.factory(100)))
        self.assertTrue(tree.search(Node.factory(99)))
        self.assertEqual(1, tree.root_node.left.value)
        self.assertEqual(11, tree.root_node.left.right.value)

    def test_deletion_of_root_node(self):
        tree = Tree()
        tree.insert(Node.factory(12))
        tree.insert(Node.factory(10))
        tree.insert(Node.factory(11))
        tree.insert(Node.factory(1))
        tree.insert(Node.factory(100))
        tree.insert(Node.factory(99))
        tree.delete(Node.factory(12))
        self.assertFalse(tree.search(Node.factory(12)))
        self.assertTrue(tree.search(Node.factory(10)))
        self.assertTrue(tree.search(Node.factory(11)))
        self.assertTrue(tree.search(Node.factory(1)))
        self.assertTrue(tree.search(Node.factory(100)))
        self.assertTrue(tree.search(Node.factory(99)))
        self.assertEqual(10, tree.root_node.value)
        self.assertEqual(1, tree.root_node.left.value)
        self.assertEqual(11, tree.root_node.right.value)
        self.assertEqual(100, tree.root_node.right.right.value)
        self.assertEqual(99, tree.root_node.right.right.left.value)